name: Website Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create simple test file
        run: |
          echo "console.log('Running automated test...')" > test.js
          echo "console.log('✅ Website structure verified!')" >> test.js

      - name: Run test file
        run: node test.js
